# Generated by Django 5.1.5 on 2025-02-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('from_user_items_confirmed', models.BooleanField(default=False)),
                ('to_user_items_confirmed', models.BooleanField(default=False)),
                ('session_id', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchanger_session', models.CharField(max_length=100)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
