# Generated by Django 5.1.5 on 2025-02-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0002_selecteditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecteditem',
            name='exchanger_session',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
