# Generated by Django 5.1.5 on 2025-02-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0004_remove_exchange_timestamp_exchange_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='from_user_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchange',
            name='session_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='to_user_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
