# Generated by Django 5.1.5 on 2025-02-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0005_exchange_from_user_confirmed_exchange_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='session_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
