# Generated by Django 5.1.5 on 2025-02-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0006_alter_exchange_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='from_user_confirmed',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='to_user_confirmed',
        ),
    ]
