# Generated by Django 5.1.5 on 2025-02-23 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0007_remove_exchange_from_user_confirmed_and_more'),
        ('my_account', '0017_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='from_user_items_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchange',
            name='session_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='to_user_items_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_account.inventoryitem'),
        ),
    ]
