# Generated by Django 5.1.5 on 2025-02-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
