# Generated by Django 5.1.5 on 2025-02-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0003_alter_profile_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet_balance',
            field=models.FloatField(default=0),
        ),
    ]
