# Generated by Django 5.1.5 on 2025-02-10 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0004_inventoryitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL),
        ),
    ]
