# Generated by Django 5.1.5 on 2025-02-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0005_alter_profile_wallet_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='item_value',
            new_name='price',
        ),
    ]
