# Generated by Django 5.1.5 on 2025-02-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0005_alter_inventoryitem_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trade_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
