# Generated by Django 5.1.5 on 2025-02-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0006_profile_trade_url_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
