# Generated by Django 5.1.5 on 2025-02-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0007_alter_friendship_from_user_alter_friendship_to_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
