# Generated by Django 5.1.5 on 2025-02-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0007_alter_inventoryitem_item_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
