# Generated by Django 5.1.5 on 2025-02-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0008_alter_inventoryitem_item_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='drop_chance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
