# Generated by Django 5.1.5 on 2025-02-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0006_rename_item_name_inventoryitem_name_and_more'),
        ('my_account', '0009_alter_profile_uid'),
    ]

    operations = [
    ]
