# Generated by Django 5.1.5 on 2025-02-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0009_alter_profile_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
