# Generated by Django 5.1.5 on 2025-02-19 17:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0013_chatroom_message_chat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
