# Generated by Django 5.1.5 on 2025-02-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0014_alter_chatroom_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_room',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
