# Generated by Django 5.1.5 on 2025-02-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0015_remove_message_chat_room_delete_chatroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
