# Generated by Django 5.1.5 on 2025-02-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
