# Generated by Django 5.1.5 on 2025-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.CharField(choices=[('Free Cases', 'Free Cases'), ('CS 2 Cases', 'CS 2 Cases'), ('Sticker Cases', 'Sticker Cases'), ('Limited Offers', 'Limited Offers'), ('Knife Cases', 'Knife Cases'), ('Pistol Cases', 'Pistol Cases'), ('Fifty-Fifty Cases', 'Fifty-Fifty Cases'), ('Custom Cases', 'Custom Cases'), ('Developer Cases', 'Developer Cases')], default='CS 2 Cases', max_length=50),
        ),
    ]
