# Generated by Django 5.1.5 on 2025-02-24 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WearRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UpgradeItemsWearRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wear_ratings', to='upgrader.upgradeitem')),
                ('wear_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_items', to='upgrader.wearrating')),
            ],
        ),
    ]
