# Generated by Django 5.1.5 on 2025-02-15 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgrader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wearrating',
            name='color',
        ),
        migrations.AlterField(
            model_name='upgradeitemswearratings',
            name='wear_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_items', to='upgrader.wearrating'),
        ),
    ]
